version: '3.5'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk

  logstashshipper:
    build:
      context: logstash-shipper/
    volumes:
      - ./logstash-shipper/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash-shipper/pipeline:/usr/share/logstash/pipeline:ro
      - ../springbootelkdemo/spring-boot-elk.log:/tmp/spring-boot-elk.log:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - redismaster

  logstashindexer:
    build:
      context: logstash-indexer/
    volumes:
      - ./logstash-indexer/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash-indexer/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5001:5001"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
  redismaster:
    build:
      context: redis/
    ports:
      - "6739:6739"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
